### ISSUE TITLE
[QUESTION] Is this planned for future versions?

### ISSUE THREAD

**Issue by SlimefrogSocial** [Chumbanotz/AbyssalDepths#1]
I am making a server/modpack and I am looking to see all my 1.12.2 mods that won't be updating and removing ones that are not updating. This is an amazing mod and I would hate to remove it so I am reaching out to ask, are you planning on updating to 1.15 and above? Thank you for reading!

**Comment by Chumbanotz** [comment]
I am, and it is mostly finished, although I may not keep the world generation (the seaweed and 'rock' formations made from hardened clay) since vanilla has enough already in the oceans, or maybe I'll keep it as optional. Not sure what I will call the generic 'fish' mob that represented vanilla Minecraft's fish item.

**Comment by SlimefrogSocial** [comment]
Thank you!
