### ISSUE TITLE
Sailfish and swordfish spawn egg doesn't work or they don't work

### ISSUE THREAD

**Issue by NEFFLEAFF** [Chumbanotz/AbyssalDepths#2]

**Comment by Chumbanotz** [comment]
Which version? Do any other spawn eggs not work?

**Comment by NEFFLEAFF** [comment]
in the new version for 1.16.5, the other spawn eggs work like clownfish and sea serpent spawn egg

**Comment by NEFFLEAFF** [comment]
![Captura](https://user-images.githubusercontent.com/69360168/111242352-9da73f80-85c4-11eb-8b4c-651ccd0baf31.PNG)
also the /summon doesn't work with sailfish but it works with other fish

**Comment by Chumbanotz** [comment]
In your .minecraft folder, there is a logs folder that should have a file called latest.log, which is created from the last time you ran the game. If you could post that file here that would allow me to see what is wrong. Try and summon the sailfish or swordfish again if you ran minecraft again since yesterday.

**Comment by NEFFLEAFF** [comment]
[latest.log](https://github.com/Chumbanotz/AbyssalDepths/files/6151003/latest.log)
i think this one it's the latest log

**Comment by Chumbanotz** [comment]
Thank you, I now know what the issue is.
